### ISSUE TITLE
NPM executable cannot find node

### ISSUE THREAD

**Issue by tbo** [prabirshrestha/typescript-language-server#23]
The cli.js throws the following error messages:

```
$ typescript-language-server --stdio
env: node\r: No such file or directory
```

I'm running this under MacOS. I assume, that this package was build under MS Windows, which is usually using CR+LF.

**Comment by prabirshrestha** [comment]
I did create the package in windows. I usually use `.gitattributes` to avoid these sort of issues. But since the compiled files are not tracked by git I now manually set the new line endings in tsconfig.json.

Can you give `v0.0.19` a try and let me know if this issue is resolved?

https://github.com/prabirshrestha/typescript-language-server/commit/880b93136376297bc3f7354e57d5d2536bd852c8

**Comment by tbo** [comment]
Works! Thanks.
