### ISSUE TITLE
Support for typescript.tsdk with tsserverPath

### ISSUE THREAD

**Issue by angelozerr** [prabirshrestha/typescript-language-server#6]
IMHO I think there are 2 problems with the tsserverPath:

 * By default `tsserver.bat` / `tsserver` is searched in the %PATH (when you install TypeScript in global npm registry). In my case I had a very old installed TypeScript and I was not able to consume navtree. I think `tsserver.bat` / `tsserver`  should be searched at first time with require.resolve like this:

```
try {
    var tsserverPath = require.resolve(".bin/" + (utils.isWindows() ? 'tsserver.cmd' : 'tsserver'));
    this.options.tsserverPath = tsserverPath;        	
}
catch(error) {}

 this.tsServerClient = new tsServerClient_1.TsServerClient({
            tsserverPath: this.options.tsserverPath || (utils.isWindows() ? 'tsserver.cmd' : 'tsserver'),
            logFile: this.options.tsserverLogFile,
            logger: this.logger
        });
```
 * IMHO I think it should be better to consume typescript/lib/tsserver.js to provide a `typescript.tsdk` settings (your tsserverPath) like VSCode does https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions

It will be more easy to use it with VSCode.

**Comment by prabirshrestha** [comment]
`typescript.tsdk` is specified in vscode settings file so this wouldn't be the best. If it was in `editorconfig` then it would be ok. I would rather have `--tsserver-path /absolute/path/to/tsserver` first and would let each editors implement their own.

I do have plans to add flags that looks something like this. `--tsserver-resolve-strategy=vscode,node_modules,global`. Given that I have seen lot of people checkin `.vscode` folder I think it is ok to to support `.vscode` settings. Might be we can even add `custom` so that each editor can implement only their resolve strategy. ` --tsserver-resolve-strategy=custom,vscode,node_modules,global --tsserver-custom-resolver=/path/to/resolve.js`.

But first I need to support for basic args `--version`.

**Comment by prabirshrestha** [comment]
You can now use `--tsserver-path` to specific the path to `tsserver`. Need v0.0.14. Make sure to append `.cmd` for windows as langserver will not append it automatically for you.

```cmd
C:\tmp\typescript-language-server>typescript-language-server --help

  Usage: typescript-language-server [options]


  Options:

    -V, --version           output the version number
    --stdio                 use stdio
    --node-ipc              use node-ipc
    --socket <port>         use socket. example: --socket=5000
    --tsserver-path <path>  absolute path to tsserver. example: --tsserver-path=c:\tsc\tsserver.cmd
    -h, --help              output usage information
```

For now I will leave this issue open since I would still like to support `--tsserver-resolve-strategy=custom,vscode,node_modules,global --tsserver-custom-resolver=/path/to/resolve.js` but this won't be enabled anytime soon. PRs welcomed for this one.

**Comment by prabirshrestha** [comment]
fixed in https://github.com/theia-ide/typescript-language-server
